### ISSUE TITLE
Memoizar/cachear la planilla para reducir tiempo de carga

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/algo2_sistema_entregas#26]
La página del sistema de entregas tarda, en mi opinión, demasiado en cargar. (Acoto que cualquier cosa por encima de 500ms cuenta, en mi opinión, como demasiado.)

Sin haber hecho profiling formal, entiendo que tarda en cargar porque se descarga los datos de Sheets para cada carga de la página frontal. Eso es lento.

Creo que perfectamente se podrían cachear esos datos por un tiempo razonable, pues apenas cambian.

Habría que ver el mecanismo, podrían hacerse con un pool o worker de uwsgi, o algo server-agnostic (Python thread?).

**Comment by dato** [comment]
Opiniones @FdelMazo @mbuchwald?

**Comment by mbuchwald** [comment]
Estoy de acuerdo que demora mucho en cargar, y que tranquilamente debe poderse catchear por un (buen) tiempo, salvo por el hecho del momento en el que se asignan grupos que deberíamos poder forzar que chequee la planilla, pero tampoco creo que sea algo demasiado complejo de hacer (digo, un mecanismo para que forzosamente chequee la planilla).

**Comment by dato** [comment]
Si estamos de acuerdo con hacer ssh a mano cuando toque, entonces el mecanismo es un simple `systemctl resart`, o `touch xxx.ini`.

Alternativamente, se puede agregar un endpoint tipo `/invalidate`, que si se visita a mano (ya sea con el navegador, ya sea con una herramienta tipo curl), invalide/refresque la cache.

¿Alguna preferencia y/o idea alternativa? (Mi preferencia es por systemctl, porque no hace falta código adicional. Pero estoy dispuesto a implementar la segunda si se te hace mucho más cómodo, e.g. hay que hacerlo más de tres veces al cuatrimestre.)

**Comment by FdelMazo** [comment]
No se mucho del tema como para opinar alguna mejor alternativa.

**Comment by dato** [comment]
Esto se arregló usando el paquete cachetools en #31 (13ef3b8bd1250fb080106d98f768062a22551568).
